//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jallikattu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPostsTable
    {
        public int PostID { get; set; }
        public string ImageURL { get; set; }
        public string BlogTitle { get; set; }
        public string BlogContent { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string Slug { get; set; }
        public string Category { get; set; }
    }
}
