//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jallikattu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CattleBreedsTable
    {
        public int CattleID { get; set; }
        public string BreedName { get; set; }
        public string Utility { get; set; }
        public string Origin { get; set; }
        public string Distribution { get; set; }
        public string Description { get; set; }
        public string ImageURL { get; set; }
        public int Createdby { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    }
}
