//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jallikattu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventsTable
    {
        public int EventID { get; set; }
        public string UserName { get; set; }
        public string MobileNo { get; set; }
        public string EventName { get; set; }
        public System.DateTime EventDate { get; set; }
        public string EventLocation { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public int Status { get; set; }
    }
}
