//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jallikattu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public string UserId { get; set; }
        public decimal TotalAmount { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string OrderStatus { get; set; }
    
        public virtual OrderItem OrderItem { get; set; }
    }
}
